name: Tests & Linting

on: workflow_call

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-golang-${{ hashFiles('./go.sum') }}

      - name: Lint
        run: go vet

      - name: Build
        run: go build ./...

      - name: Go test
        run: go test ./... -cover -race
